spring:
  application:
    name: 'DorlovaNailTelegramBot'
#  datasource:
#    driver-class-name: ${MYSQL_DATABASE_DRIVER}
#    url: jdbc:mysql://${MYSQL_DATABASE_HOST}:${MYSQL_DATABASE_PORT}
##    /${MYSQL_DATABASE_NAME}
#    username: ${MYSQL_ROOT_USER}
#    password: ${MYSQL_ROOT_PASSWORD}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dorlova_nail
    username: root
    password: q12345678
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect